"""ez-pixel init — auto-generated by ezcoder pixel install.

This file initializes error tracking. Importing it (which the install step
wires into your entry file) registers the global Python error handlers.
"""
import os

import ez_pixel

ez_pixel.init_pixel(
    project_key=os.environ.get("EZCODER_PIXEL_KEY") or "pk_live_607f1eb4e8e57e1b1f4a0cfa22b37774",
    ingest_url="https://pixel-server.ngrout70.workers.dev/ingest",
)
