"""add prospect_signals table

Revision ID: a0e8a88f7801
Revises: d4e5f6a7b8c9
Create Date: 2026-06-12 10:47:41.003038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0e8a88f7801'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'dismissed', name='prospectsignalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['lead_prospects.id'], name=op.f('fk_prospect_signals_prospect_id_lead_prospects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_prospect_signals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prospect_signals')),
    sa.UniqueConstraint('workspace_id', 'prospect_id', 'signal_type', name='uq_prospect_signals_workspace_prospect_type')
    )
    op.create_index('ix_prospect_signals_prospect', 'prospect_signals', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_prospect_signals_workspace_id'), 'prospect_signals', ['workspace_id'], unique=False)
    op.create_index(
        'ix_prospect_signals_workspace_type_strength',
        'prospect_signals',
        ['workspace_id', 'signal_type', 'strength'],
        unique=False,
        postgresql_ops={'strength': 'DESC'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_prospect_signals_workspace_type_strength',
        table_name='prospect_signals',
        postgresql_ops={'strength': 'DESC'},
    )
    op.drop_index(op.f('ix_prospect_signals_workspace_id'), table_name='prospect_signals')
    op.drop_index('ix_prospect_signals_prospect', table_name='prospect_signals')
    op.drop_table('prospect_signals')
    # ### end Alembic commands ###
