// Safe arithmetic evaluator for lead-magnet calculator formulas.
//
// Calculator content_data formulas (generated by the AI builder) look like
// "input1 * (input2 / 100)" or "calc1 * 12" — variable references plus the
// arithmetic operators + - * / and parentheses. We must never run these
// through eval()/Function() on a public page, so this module implements a tiny
// recursive-descent parser that only understands numbers, named variables, and
// the four arithmetic operators. Anything else evaluates to null.

type Token =
  | { type: "number"; value: number }
  | { type: "ident"; value: string }
  | { type: "op"; value: "+" | "-" | "*" | "/" }
  | { type: "lparen" }
  | { type: "rparen" };

function tokenize(input: string): Token[] | null {
  const tokens: Token[] = [];
  let i = 0;

  while (i < input.length) {
    const ch = input[i];

    if (ch === " " || ch === "\t" || ch === "\n") {
      i++;
      continue;
    }

    if (ch === "+" || ch === "-" || ch === "*" || ch === "/") {
      tokens.push({ type: "op", value: ch });
      i++;
      continue;
    }

    if (ch === "(") {
      tokens.push({ type: "lparen" });
      i++;
      continue;
    }

    if (ch === ")") {
      tokens.push({ type: "rparen" });
      i++;
      continue;
    }

    if ((ch >= "0" && ch <= "9") || ch === ".") {
      let num = "";
      while (i < input.length && /[0-9.]/.test(input[i])) {
        num += input[i];
        i++;
      }
      const value = Number(num);
      if (!Number.isFinite(value)) return null;
      tokens.push({ type: "number", value });
      continue;
    }

    if (/[a-zA-Z_]/.test(ch)) {
      let ident = "";
      while (i < input.length && /[a-zA-Z0-9_]/.test(input[i])) {
        ident += input[i];
        i++;
      }
      tokens.push({ type: "ident", value: ident });
      continue;
    }

    // Unknown character — refuse to evaluate.
    return null;
  }

  return tokens;
}

/**
 * Evaluate a calculator formula against a scope of resolved variable values.
 * Returns null when the formula is malformed, references an unknown variable,
 * or produces a non-finite result (e.g. division by zero).
 */
export function evaluateFormula(
  formula: string,
  scope: Record<string, number>,
): number | null {
  const tokens = tokenize(formula);
  if (!tokens) return null;

  let pos = 0;

  const peek = (): Token | undefined => tokens[pos];

  // expr := term (("+" | "-") term)*
  const parseExpr = (): number | null => {
    let left = parseTerm();
    if (left === null) return null;

    while (peek()?.type === "op") {
      const op = peek() as { type: "op"; value: string };
      if (op.value !== "+" && op.value !== "-") break;
      pos++;
      const right = parseTerm();
      if (right === null) return null;
      left = op.value === "+" ? left + right : left - right;
    }
    return left;
  };

  // term := factor (("*" | "/") factor)*
  const parseTerm = (): number | null => {
    let left = parseFactor();
    if (left === null) return null;

    while (peek()?.type === "op") {
      const op = peek() as { type: "op"; value: string };
      if (op.value !== "*" && op.value !== "/") break;
      pos++;
      const right = parseFactor();
      if (right === null) return null;
      if (op.value === "/") {
        if (right === 0) return null;
        left = left / right;
      } else {
        left = left * right;
      }
    }
    return left;
  };

  // factor := number | ident | "(" expr ")" | ("+" | "-") factor
  const parseFactor = (): number | null => {
    const token = peek();
    if (!token) return null;

    if (token.type === "op" && (token.value === "+" || token.value === "-")) {
      pos++;
      const operand = parseFactor();
      if (operand === null) return null;
      return token.value === "-" ? -operand : operand;
    }

    if (token.type === "number") {
      pos++;
      return token.value;
    }

    if (token.type === "ident") {
      pos++;
      const value = scope[token.value];
      if (typeof value !== "number" || !Number.isFinite(value)) return null;
      return value;
    }

    if (token.type === "lparen") {
      pos++;
      const inner = parseExpr();
      if (inner === null) return null;
      if (peek()?.type !== "rparen") return null;
      pos++;
      return inner;
    }

    return null;
  };

  const result = parseExpr();
  if (result === null) return null;
  if (pos !== tokens.length) return null; // trailing tokens => malformed
  if (!Number.isFinite(result)) return null;
  return result;
}
